imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id:  ~
    fragments:       ~
    http_method_override: true

twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

hwi_oauth:
    firewall_name: oauth2_area
    resource_owners:
        oauth2:
            type:                oauth2
            client_id:           %oauth2_client_id%
            client_secret:       %oauth2_client_secret%
            access_token_url:    %oauth2_url%/oauth/v2/token
            authorization_url:   %oauth2_url%/oauth/v2/auth
            infos_url:           %oauth2_url%/api/me
            user_response_class: HWI\Bundle\OAuthBundle\OAuth\Response\AdvancedPathUserResponse
            paths:
                identifier: id
                nickname:   username
                email:      email
                realname:   realname

snc_redis:
    clients:
        default:
            alias: default
            type:  predis
            dsn:   redis://%redis_host%
