hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

connect_login:
    path: /login/check-connect

logout:
    pattern: /logout

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
