# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    providers:
        oauth2_provider:
            id: hwi_oauth.user.provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        oauth2_area:
            pattern: ^/
            security:   true
            anonymous:  true
            oauth:
                resource_owners:
                    connect: connect_login
                login_path: /login
                check_path: /login_check
                use_forward: false
                failure_path: /login
                oauth_user_provider:
                    service: hwi_oauth.user.provider
